<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>[Your Project Name]</title>
  <link rel="stylesheet" href="style.css"> </head>
<body>
  <header class="header">
    <div class="container">
      <a href="#" class="logo">
        <img src="images/cover.jpg" alt="[Project Name] Cover Image"> </a>
      <h1>[Your Project Name]</h1>
      <p class="description">[One-line description of your project]</p>
      <nav class="navigation">
        <ul>
          <li><a href="#features">Features</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="[deployed_project_url]" class="button">Explore Project</a></li> </ul>
      </nav>
    </div>
  </header>

  </body>
</html>

